# Generated by Django 5.2.7 on 2025-10-15 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес стройплощадки')),
                ('construction_stage', models.CharField(max_length=100, verbose_name='Стадия строительства')),
            ],
            options={
                'verbose_name': 'Строительство объекта',
                'verbose_name_plural': 'Строительство объектов',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
                ('department', models.CharField(max_length=50, verbose_name='Отдел')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название материала')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('available_quantity', models.IntegerField(verbose_name='Доступное количество')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='Никнейм')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_login', models.DateTimeField(verbose_name='Поледний вход')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Расход материала')),
                ('construction_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.constructionobjects', verbose_name='Строительство объекта')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_app.materials', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Использование материалов',
                'verbose_name_plural': 'Использование материалов',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('construction_period', models.IntegerField(verbose_name='Срок строительства')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Бюджет')),
                ('start_date', models.DateField(verbose_name='Дата приема в работу')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_app.customers', verbose_name='Заказчик')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_app.employees', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок документа')),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
                ('file_link', models.URLField(verbose_name='Ссылка на файл')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AddField(
            model_name='constructionobjects',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.projects', verbose_name='Проект'),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100, verbose_name='Специальность команды')),
                ('member_count', models.IntegerField(verbose_name='Количество членов в команде')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.employees', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
            },
        ),
    ]
