# Generated by Django 5.2.7 on 2025-10-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='supplier',
        ),
    ]
